language: node_js
node_js:
- '5.0'
- 'stable'
sudo: false
branches:
  except:
  - "/^v[0-9\\.]+/"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  matrix:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  global:
    - CXX=g++-4.8
    - secure: Waeeo/oid+a1OH+NjEME9KXNrqCny9a3iSX4QcUjApJvU3WDS58ELqvcIxbO29pJHcsvrbunhd/siVQ32RTFzkyz6l+jBAj+eHQH+MfCNA7en/0Jx5idPt7A6WARKBPdv81cTdv7oWr5iRZMrpX1JpN1h+lqNH7FrZ4yL8pt9vZWEQanUaL/6DCXh0hUPUXg+8MQ0/UbA3DoT1NfeOjPUK8JUKQjUZVM5f+pPsTCkbzkoQZho5jdFIhg7jWZX+QrqIuZdN+AtizmS+kI48h/DafN3T3w2lO5JS/YHBel7EcsW/X4WcfJrR1Av7QlOY/tLwzAkD/Ys3RMnK+a9EuBbE8wOGGWY4wmSYOgh4yZTKAHe6lEHKX/ztQFotB9pBcx1OjT6s/4k/V+VRXM6TfAS2hoB5lxL4ZX++QPVXRQD8lZGP+EJ3NRdtn05BMJiruhMgxnA6jiDOm8pp5iIPc4goG2GKbCgNFocXIz5mYBPxRC6WeiD8jjE4TA1XcoDqGNPuJaNOGyKrEOcyhPdvZ6B6aDGNq6FT7fXzvK9WnZEFKpEqnCR33TBOOxUWZCKh/Ce9xrySZowc3Wa6H7Tc7AR6hW2e/Egkv99DKOrbXY+20mjvnKmuJLYy1Tm9/Q5cz90/eVzxwuivfwWRRJPELh4VuzkODbM3Pn1vOAMPV10ng=
matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-canary
before_install:
- npm config set spin false
- npm install -g coveralls pr-bumper
- pr-bumper check
install:
- npm install
- bower install
script:
- npm run lint
- ember try:one $EMBER_TRY_SCENARIO --- ember test
after_success:
- .travis/publish-coverage.sh
before_deploy:
- pr-bumper bump
deploy:
  provider: npm
  email: npm.ciena@gmail.com
  skip_cleanup: true
  api_key:
    secure: B4UIGF/KLwS3vOpemKDRLtDjtl8rl4bpYClQEcjzAALx23nieKFCKXEKbOM5W7U8XNx0ygWuYNcaTnuKP6G67ijCdZRP7SnRPc5hP+F0Hhv35i2VGcUaczqCJpkuaC/8ncjoR9asBTFyNzVlUag5/ZdmCzFBvn+PUpSMUBsUNxAhulDXUsuG8XeCOEAt8Bz1Ej4oN4DP8dDJZQs+vCgZl6156YDHk9ZHWyGdwMmA2CI7YFq6iy5Kc+QvTu25Ymjbz5HeIY8c6fTqYbpvYMm1zBLWFFRmrv93O87YCv61Lw7F+GbxZw6KYn1ufL7puGQ+ffgiXqZR8OZfm6DMHHIGl//wE5OJ6qbxLos/GFAakUCKdGtF6OEjKM/0tW6OD98i0FBiAxXYF9mSy8yC2npFKBDkvW2ghsOZTFuyIcfCnbp4iahJWXaKNpStdPIeFxq52fcjMx1cE4+XOdjwQ1hx/FeVpJrgNn/zVGzqTmzXmrWzMZ9T3ANB8xT6JpAHzP+adap3GUu5kBwRYjWyvVvz0Mh8xF5s2efam9z6MI1Blt+uRqt9wEZTa/8Im44IDXLKyYPBU9R81RFTkiDQLzTp0Ww7DMjeqmFU4M8JkjgVfDsKtIJafvnrIPGxDrNgq5TlC73Up46FS/lAzPTkIf/PgnD8chrtc44gHJtm2rnmrEw=
  on:
    branch: master
    condition: "$EMBER_TRY_SCENARIO = 'default'"
    node: 'stable'
    tags: false
after_deploy:
- .travis/publish-gh-pages.sh
notifications:
  slack:
    secure: fYjd30ji8nQmRPbcoYGpMwsjj4Ul7YT/QeKaU8qPz9BwQKXFnv3Rw6kv3+yGZJR1KrdyfueYhMC/no5M8RYVfoamECmuM1hCQGNnqkn6RUbhkKhcetzqrjymqH1Qa6+Hs7flPPM+et1757zx3hIYYdxjFU3OfK728SXSOhV8XfEqykAmZKy+waH2hpXfCmj+znYhgZbXeKdH5EJarWS2T7lpKJ3PNY1SmX+YZpNUqQV3+Xdcbr3Ia92tfcPzgn1p2RVB8bVHuOdsDodRMYAlUFYi9A20fZTjQuvOCp0YGPwoKTutn1kKuqSe1EG9bylbUoz3UxrYeyAivuriYLfRRrCTOeKH5JJlwkZ93mUV+FD4mSHQDQ92GF3bXJd6NHudQzD4qGTngz98HS9JBdaWqjJiN47I+w4STb6kk55gu7pZTF0Un+QqEmkADcQqbVdsE9Fbl0g0XUZxGxghews5U6bOO/u45MdhPwZWSsRgAdhshq3kdwBb70khHuvU8nK+x+fjZ+8O9yK8fCwib388IZasL5JPqnfd57MQ684bs5OnmgHcY6HFcYHF0ejCga+j/E+EN0QJQ8693sLMlw581YvNY0ZF/7Av/x5oCvYt37xm7ZMao5NhqfRFNDnoDIlJ3AnuD2wtM62JUjCOXvbkphWPqG9F2N4zmG0oCUKczhg=
